export const darkTheme = {
    body: "#282c35",
    text: "white",
    quoteBorder: "lightgray",
    quoteBackground: "#272c42",
    code: {
        color: "#c3cee3",
        background: "#1b2326",
        selection: {
            color: "#c3cee3",
            background: "#363636",
        },
        codeColor: "#fd9170",
        token: {
            atRule: "#c792ea",
            attributeName: "#ffcb6b",
            attributeValue: "#c3e88d",
            attribute: "#c3e88d",
            boolean: "#c792ea",
            builtIn: "#ffcb6b",
            cData: "#80cbc4",
            char: "#80cbc4",
            class: "#ffcb6b",
            className: "#f2ff00",
            comment: "orange",
            constant: "#c792ea",
            deleted: "#f07178",
            docType: "#546e7a",
            entity: "#f07178",
            function: "#c792ea",
            hexCode: "#f2ff00",
            id: "#c792ea",
            important: "#c792ea",
            inserted: "#80cbc4",
            keyword: "#c792ea",
            number: "#fd9170",
            operator: "#89ddff",
            prolog: "#546e7a",
            property: "#80cbc4",
            pseudoClass: "#c3e88d",
            pseudoElement: "#c3e88d",
            punctuation: "#89ddff",
            regex: "#f2ff00",
            selector: "#f07178",
            string: "red",
            symbol: "#c792ea",
            tag: "#f07178",
            unit: "#f07178",
            url: "#fd9170",
            variable: "#f07178",
        },
    },
};
