export const lightTheme = {
    body: "#FFF",
    text: "#363537",
    quoteBorder: "#272c42",
    quoteBackground: "whitesmoke",
    code: {
        color: "#000203",
        background: "#fafafa",
        selection: {
            color: "#cceae7",
            background: "#cceae7",
        },
        codeColor: "#f76d47",
        token: {
            atRule: "#7c4dff",
            attributeName: "#DD4A68",
            attributeValue: "#f6a434",
            attribute: "#f6a434",
            boolean: "#7c4dff",
            builtIn: "#DD4A68",
            cData: "#DD4A68",
            char: "#DD4A68",
            class: "#DD4A68",
            className: "#6182b8",
            comment: "#aabfc9",
            constant: "#7c4dff",
            deleted: "#e53935",
            docType: "#aabfc9",
            entity: "#e53935",
            function: "#7c4dff",
            hexCode: "#f76d47",
            id: "#7c4dff",
            important: "#7c4dff",
            inserted: "#DD4A68",
            keyword: "#7c4dff",
            number: "#f76d47",
            operator: "#DD4A68",
            prolog: "#aabfc9",
            property: "#DD4A68",
            pseudoClass: "#f6a434",
            pseudoElement: "#f6a434",
            punctuation: "#DD4A68",
            regex: "#6182b8",
            selector: "#e53935",
            string: "#f6a434",
            symbol: "#7c4dff",
            tag: "#e53935",
            unit: "#f76d47",
            url: "#e53935",
            variable: "#e53935",
        },
    },
};
